language: java
sudo: required 
dist: trusty
before_install:
- chmod +x ./gradlew
script:
- ./gradlew setupDecompWorkspace
- ./gradlew build
cache:
  directories:
  - ./build
deploy:
  provider: releases
  api_key: ""
  file: "./build/libs/gregtech-5.10.41.jar"
  skip_cleanup: true
