language: java
sudo: required 
dist: trusty
before_install:
- chmod +x ./gradlew
script:
- ./gradlew setupDecompWorkspace
- ./gradlew build
deploy:
  provider: releases
  api_key: "32a23fd74ed882f48899745d521cda242df8a5ec"
  file: "./build/libs/gregtech-5.10.41.jar"
  skip_cleanup: true
